apiVersion: 1

datasources:
  - name: Netdata
    type: prometheus
    access: proxy
    url: http://oci-netdata:19999/api/v1/allmetrics?format=prometheus
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeInterval: "1s"
      httpMethod: GET
